# TODO(@connorbaker): Copied from 13.3 -- should be regenerated.
# generated by hand to avoid exposing all private frameworks
# frameworks here are only the necessary ones used by public frameworks.
# To find these, @connorbaker built packages depending on public frameworks
# and added the missing frameworks to this list.
{ objc4 }:
# NOTE: Must be a function so we can use callPackage in `default.nix`
{
  AudioToolboxCore = { }; # AudioToolbox
  CollectionViewCore = { }; # AppKit
  CoreSymbolication = { }; # hepmc3
  DebugSymbols = { }; # llvmPackages_8.lldb
  DisplayServices = { libobjc = objc4; }; # macchina
  MultitouchSupport = { }; # chuck
  PassKitCore = { }; # PassKit
  PassKitMacHelper = { }; # PassKit
  SkyLight = { }; # spacebar
  UIFoundation = { };
}
